version: '3'
services:
  web:
    build: .
    command: bundle exec rails server -p ${PORT} -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
  db:
    image: postgres:10.0
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
